--- !<tag:barectf.org,2020/3/config>

options:
  code-generation:
    prefix:
      file-name: freertos_trace
      identifier: freertos_barectf_

trace:
  environment:
    domain: kernel
    sysname: FreeRTOS

  type:
    # Add standard field type aliases.
    $include:
      - stdint.yaml
      - stdmisc.yaml

    native-byte-order: little-endian

    clock-types:
      freertos_barectf:
        frequency: 1000000000
        $c-type: uint64_t

    data-stream-types:
      kernel:
        $is-default: true

        $default-clock-type-name: freertos_barectf

        packet-context-field-type-extra-members:
          - cpu_id: uint32

        $include:
          - scheduler_events.yaml
